version: '3.1'


services:

  nginx:

    image: nginx:latest

    container_name: nginx1

    ports:
      - 8091:80
      - 443:443

    volumes:
      - ${APP_PATH_NGINX_CONF}:/etc/nginx/conf.d
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ${APP_PATH_NGINX_LOG}:/var/log/nginx/

    links:
      - php
    working_dir: ${APP_PATH_CONTAINER}

  php:
    # Билдим с помощью dockerfile указав директорию где он лежит
    build: ./php
    container_name: php1
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}

  php-cli:
    build: ./php-cli
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    links:
      - db
      - redis
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    tty: true


  redis:
    container_name: redis1
    image: redis
    ports:
      - 63792:6379

  db:
    image: mariadb
    container_name: mariadb1
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql




  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    ports:
      - 8088:80

  node:
    image: node
    working_dir: ${APP_PATH_CONTAINER}
    volumes:
      - ./:${APP_PATH_CONTAINER}

